### ISSUE TITLE
Stuck after COS, no transition state optimization

### ISSUE THREAD

**Issue by kantundpeterpan** [eljost/pysisyphus#133]
Hello!

#### System
Ubuntu 19.10
pysisyphus 0.6
xtb 6.4.0
####

My .pysisyphusrc:
```
[xtb]
cmd=xtb
```
---
I ran the `02_alanine_dipeptide_iso_xtb` example.
The Growstring part runs fine, but then pysis gets stuck.

<details>
  <summary>pysis.log</summary>

 ```text
                           d8b                            888
                           Y8P                            888
                                                          888
88888b.  888  888 .d8888b  888 .d8888b  888  888 88888b.  88888b.  888  888 .d8888b
888 "88b 888  888 88K      888 88K      888  888 888 "88b 888 "88b 888  888 88K
888  888 888  888 "Y8888b. 888 "Y8888b. 888  888 888  888 888  888 888  888 "Y8888b.
888 d88P Y88b 888      X88 888      X88 Y88b 888 888 d88P 888  888 Y88b 888      X88
88888P"   "Y88888  88888P' 888  88888P'  "Y88888 88888P"  888  888  "Y88888  88888P'
888           888                            888 888
888      Y8b d88P                       Y8b d88P 888
888       "Y88P"                         "Y88P"  888                            

Version 0.6 (Python 3.9.2, NumPy 1.20.2, SciPy 1.6.2)
Git commit d86a8927e4c24872f570363a0a571d8e5225e1fd
Executed at Tue Mar 30 10:30:37 2021 on 'haina-Ubs19'
Platform: Linux-5.3.0-64-generic-x86_64-with-glibc2.30

If pysisyphus benefitted your research please cite:

	https://doi.org/10.1002/qua.26390

Good luck!

{'assert': {'opt.is_converged': True,
            'ts_geom.energy': -32.9647645,
            'ts_opt.cur_cycle': 18},
 'calc': {'charge': 0, 'mult': 1, 'pal': 4, 'type': 'xtb'},
 'cos': {'fix_ends': True, 'max_nodes': 9, 'type': 'gs'},
 'geom': {'fn': ['ala_start.xyz', 'ala_end.xyz'], 'type': 'dlc'},
 'opt': {'align': False,
         'dump': True,
         'stop_in_when_full': 3,
         'type': 'string'},
 'preopt': {'dump': True,
            'geom': {'type': 'redund'},
            'max_cycles': 100,
            'overachieve_factor': 3,
            'preopt': 'both',
            'strict': False,
            'thresh': 'gau_loose',
            'trust_max': 0.3,
            'type': 'rfo'},
 'tsopt': {'do_hess': True,
           'dump': True,
           'h5_group_name': 'tsopt',
           'hessian_recalc': 3,
           'overachieve_factor': 3,
           'thresh': 'gau',
           'trust_max': 0.3,
           'type': 'rsprfo'}}

Read 2 geometries.
                       #################################
                       # RUNNING FIRST PREOPTIMIZATION #
                       #################################

Input structure: Geometry(C6_N2_O2_H12, 22 atoms)

Spent 0.0 s preparing the first cycle.
cycle   max(force)    rms(force)     max(step)     rms(step)       s/cycle
    0     0.022124     0.004464     0.030479     0.009862          1.1
    1     0.004109     0.000860     0.012253     0.003843          1.2
    2     0.001079     0.000338     0.021683     0.005954          0.9
    3     0.001074     0.000220     0.016664     0.005091          1.1
    4     0.000504     0.000187     0.009102     0.002659          1.1
Converged!

Final summary:
            	max(forces, internal): 0.000504 hartree/(bohr,rad)
            	rms(forces, internal): 0.000187 hartree/(bohr,rad)
        	max(forces,cartesian): 0.001226 hartree/bohr
        	rms(forces,cartesian): 0.000350 hartree/bohr
        	energy: -32.97301407 hartree
Wrote final, hopefully optimized, geometry to 'first_pre_final_geometry.xyz'

Preoptimization of first geometry converged!
Saved final preoptimized structure to 'first_preopt.xyz'.
RMSD with initial geometry: 0.093104 au

                        ################################
                        # RUNNING LAST PREOPTIMIZATION #
                        ################################

Input structure: Geometry(C6_N2_O2_H12, 22 atoms)

Spent 0.0 s preparing the first cycle.
cycle   max(force)    rms(force)     max(step)     rms(step)       s/cycle
    0     0.021902     0.004590     0.103899     0.017837          0.7
    1     0.004969     0.001004     0.031337     0.006666          1.1
    2     0.001634     0.000388     0.021343     0.007414          1.2
    3     0.001321     0.000251     0.013087     0.005147          0.6
    4     0.000463     0.000150     0.012757     0.004310          0.6
Converged!

Final summary:
            	max(forces, internal): 0.000463 hartree/(bohr,rad)
            	rms(forces, internal): 0.000150 hartree/(bohr,rad)
        	max(forces,cartesian): 0.000557 hartree/bohr
        	rms(forces,cartesian): 0.000232 hartree/bohr
        	energy: -32.97312962 hartree
Wrote final, hopefully optimized, geometry to 'last_pre_final_geometry.xyz'

Preoptimization of last geometry converged!
Saved final preoptimized structure to 'last_preopt.xyz'.
RMSD with initial geometry: 0.126111 au


Read 2 geometries.
Path with 2 moving images.
                           #########################
                           # RUNNING GROWINGSTRING #
                           #########################

Input structure: ChainOfStates, 4 images, (C6_N2_O2_H12, 22 atoms) per image

Spent 0.0 s preparing the first cycle.
cycle   max(force)    rms(force)     max(step)     rms(step)       s/cycle
    0     0.021637     0.004573     0.021637     0.004573          2.4
	String=2+2 HEI=03/04 (E_max-E_0)=17.3 kJ/mol
    1     0.063833     0.007900     0.063833     0.007900          2.1
	String=3+3 HEI=04/06 (E_max-E_0)=70.9 kJ/mol
    2     0.078473     0.011375     0.078473     0.011375          3.6
	String=4+4 HEI=04/08 (E_max-E_0)=172.0 kJ/mol
    3     0.074750     0.012154     0.074750     0.012154          4.9
	String=5+5 HEI=05/10 (E_max-E_0)=256.2 kJ/mol
    4     0.059788     0.009967     0.059788     0.009967          5.3
	String=Full HEI=05/11 (E_max-E_0)=203.2 kJ/mol
    5     0.039936     0.007745     0.100000     0.018899          5.8
	String=Full HEI=05/11 (E_max-E_0)=178.8 kJ/mol
    6     0.025499     0.004990     0.100000     0.022319          5.9
	String=Full HEI=05/11 (E_max-E_0)=146.2 kJ/mol
    7     0.023550     0.004216     0.051844     0.010895          5.8
	String=Full HEI=05/11 (E_max-E_0)=120.3 kJ/mol
Converged!

Wrote final, hopefully optimized, geometry to 'final_geometries.trj'
```
</details>

The execution is not finished, but there seems nothing going on when i check in `top`

On a KeyboardInterrupt i get the following:
```
^CTraceback (most recent call last):
  File "/home/kantundpeterpan/anaconda3/envs/pysi/bin/pysis", line 8, in <module>
    sys.exit(run())
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/run.py", line 1946, in run
    return run_from_dict(run_dict, **run_kwargs)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/run.py", line 1898, in run_from_dict
    run_result = main(run_dict, restart, cwd, scheduler, dryrun)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/run.py", line 1539, in main
    ts_geom, ts_opt = run_tsopt_from_cos(
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/run.py", line 421, in run_tsopt_from_cos
    H = ts_geom.hessian
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/Geometry.py", line 758, in hessian
    hessian = self.cart_hessian
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/Geometry.py", line 736, in cart_hessian
    results = self.calculator.get_hessian(self.atoms, self._coords)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/calculators/XTB.py", line 151, in get_hessian
    results = self.run(inp, **kwargs)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/site-packages/pysisyphus/calculators/Calculator.py", line 363, in run
    result.wait()
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/subprocess.py", line 1919, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/kantundpeterpan/anaconda3/envs/pysi/lib/python3.9/subprocess.py", line 1877, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Seems like it's getting stuck waiting for the hessian. 
Can anyone help me to debug ?

**Comment by kantundpeterpan** [comment]
I tried running the hessian calculation manually and got 
`OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.`

Reinstallation of OpenBLAS with `conda install libopenblas=*=*openmp*` solved the issue.

**Comment by Hugo-Lopez-Pena** [comment]
Thanks for the hint, that definitely solved the issue!
